import React from 'react'
import Head from 'next/head'
import Navbar from '../comp/components/navbar/navbar'
import DarkTheme from '../comp/layouts/Dark'
import PageHeader from "../comp/components/Pages-header/index"
import CallToAction from '../comp/components/call-to-action/call-to-action'
import Footer from '../comp/components/footer/footer'
import MinimalArea from '../comp/components/Minimal-Area/minimal-area'
import Intro2 from '../comp/components/Intro2/intro2'
import Intro3 from '../comp/components/Intro2/intro3'

export default function About() {
    return (
        <>
        <Head >
        <title>Infobility | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <DarkTheme>
            <Navbar />
            <PageHeader />
            <div className="main-content">
      {/* <Services style="4item" /> */}
      {/* <Blogs2 /> */}
      {/* <Team /> */}
      <MinimalArea />
      <Intro2 />
      <Intro3 />
      <Intro2 />
      <CallToAction />
      <Footer />
      </div>
        </DarkTheme>
        </>
    )
}
