import React from 'react'
import Head from 'next/head'
import DarkTheme from '../comp/layouts/Dark'
import Navbar from '../comp/components/navbar/navbar'
import ContactHeader from '../comp/components/Contact-header/contact-header'
import ContactForm from '../comp/components/Contact-form/contact-form'
import Footer from '../comp/components/footer/footer'

export default function Contact() {
    // const [Trigger, setTrigger] = useState(false);
    return (
        <>
        <Head >
        <title>Infobility | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
            <DarkTheme>
            <Navbar />
        <ContactHeader />
        <div className="main-content">
          <ContactForm />

          <Footer hideBGCOLOR />
        </div>
            </DarkTheme>
        </>
    )
}
