import Head from 'next/head'
import React from "react";
import styles from '../styles/Home.module.css'
import DarkTheme from "./layouts/Dark"
import Navbar from "./components/navbar/Navbar"
import IntroWithSlider from "./components/slider/intro-with-slider"
import Services from './components/services/services'
import Footer from './components/footer/footer';
import CallToAction from './components/call-to-action/call-to-action';
import Blogs2 from './components/blog/blogs2';

export default function Home() {
  const fixedSlider = React.useRef(null);
  const MainContent = React.useRef(null);
  const navbarRef = React.useRef(null);
  const logoRef = React.useRef(null);

  React.useEffect(() => {
    setInterval(() => {
      if (fixedSlider.current) {
        var slidHeight = fixedSlider.current.offsetHeight;
      }
      if (MainContent.current) {
        MainContent.current.style.marginTop = slidHeight + "px";
      }
    }, 1000);
    var navbar = navbarRef.current;
    if (window.pageYOffset > 300) {
      navbar.classList.add("nav-scroll");
    } else {
      navbar.classList.remove("nav-scroll");
    }
    window.addEventListener("scroll", () => {
      if (window.pageYOffset > 300) {
        navbar.classList.add("nav-scroll");
      } else {
        navbar.classList.remove("nav-scroll");
      }
    });
  }, [fixedSlider, MainContent, navbarRef]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DarkTheme>
      <Navbar nr={navbarRef} lr={logoRef}/>
      <IntroWithSlider sliderRef={fixedSlider} />
      <div className="main-content">
      <Services style="4item" />
      <Blogs2 />
      <CallToAction />
      <Footer />
      </div>
      </DarkTheme>
      
    </div>
  )
}
