import React from 'react'
import Head from 'next/head'
import Navbar from '../comp/components/navbar/navbar'
import ShowcasesFullScreen from '../comp/components/Showcases-full-screen/showcases-full-screen'
import DarkTheme from '../comp/layouts/Dark'

export default function work() {
    return (
        <>
        <Head >
        <title>Infobility | Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <DarkTheme>
            <Navbar />
            <ShowcasesFullScreen />
        </DarkTheme>
        </>
    )
}
